events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    sendfile on;
    keepalive_timeout 65;

    limit_req_zone $binary_remote_addr zone=api_limit:10m rate=10r/s;

    upstream backend_upstream {
        server blue_backend:4000;
    }

    upstream frontend_upstream {
        server blue_frontend:80;
    }

    upstream face_upstream {
        server blue_face:5001;
    }

    upstream moodle_upstream {
        server moodle:80;
    }

    server {
        listen 80;
        server_name attendance-ml.duckdns.org;

        location / {
            proxy_pass http://frontend_upstream;
        }

        location /api/ {
            proxy_pass http://backend_upstream/;
        }

        location /face/ {
            proxy_pass http://face_upstream;
        }

        location /moodle/ {
            proxy_pass http://moodle_upstream/;
        }
    }
}
