events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    sendfile on;
    keepalive_timeout 65;

    limit_req_zone $binary_remote_addr zone=api_limit:10m rate=10r/s;

    # Upstreams
    upstream backend_upstream {
        server blue_backend:4000;
    }

    upstream frontend_upstream {
        server blue_frontend;
    }

    upstream face_upstream {
        server blue_face:5001;
    }

    upstream moodle_upstream {
        server moodle:80;
    }

    server {
        listen 80;
        server_name attendance-ml.duckdns.org;

        # Security headers
        add_header X-Frame-Options "SAMEORIGIN";
        add_header X-Content-Type-Options "nosniff";
        add_header X-XSS-Protection "1; mode=block";

        # FRONTEND
        location / {
            proxy_pass http://frontend_upstream;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # BACKEND API
        location /api {
            limit_req zone=api_limit burst=20;
            proxy_pass http://backend_upstream/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # FACE SERVICE
        location /face/ {
            proxy_pass http://face_upstream/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # MOODLE
        location /moodle/ {
            proxy_pass http://moodle_upstream/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}
