global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'backend'
    static_configs:
      - targets: ['blue_backend:4000']
  - job_name: 'green_backend'
    static_configs:
      - targets: ['green_backend:4000']
