server {
    listen 80;
    server_name attendance-ml.duckdns.org;

    location / {
        proxy_pass http://frontend:80;
        proxy_http_version 1.1;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;

        # React SPA fix
        try_files $uri /index.html;
    }

    location /api {
        proxy_pass http://backend:4000;
    }

    location /face {
        proxy_pass http://face-service:5001;
    }

    location /moodle {
        proxy_pass http://moodle:80;
    }
}
